# Generated by Django 4.2.1 on 2023-06-05 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
