# Generated by Django 4.2.1 on 2023-06-19 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_artwork_is_draft_artwork_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='art_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=50),
        ),
    ]
