# Generated by Django 4.2.1 on 2023-06-22 00:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0008_artwork_owner_alter_artwork_artist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='is_NFT',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artwork',
            name='is_for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
