# Generated by Django 4.2.1 on 2023-07-01 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0012_nft_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='NFT_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nft',
            name='dates',
            field= models.DateTimeField(auto_now_add=True)
        ),

        migrations.AddField(
            model_name='nft',
            name='prices_close',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='nft',
            name='prices_high',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='nft',
            name='prices_low',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='nft',
            name='prices_open',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
