# Generated by Django 4.2.1 on 2023-07-01 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0013_nft_nft_count_nft_dates_nft_prices_close_and_more'),
    ]

    operations = [

    ]
