# Generated by Django 4.2.1 on 2023-07-01 01:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0015_alter_nft_dates'),
    ]

    operations = [

    ]
