# Generated by Django 4.2.1 on 2023-07-01 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0017_alter_nft_dates'),
    ]

    operations = [

    ]
