# Generated by Django 4.2.1 on 2023-07-01 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0020_alter_nft_dates'),
    ]

    operations = [

    ]
