# Generated by Django 4.2.1 on 2023-07-01 02:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0022_remove_nft_dates'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='dates',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime.now),
            preserve_default=False,
        ),
    ]
