# Generated by Django 4.2.1 on 2023-07-01 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0023_nft_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nft',
            name='prices_close',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='prices_high',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='prices_low',
        ),
        migrations.RemoveField(
            model_name='nft',
            name='prices_open',
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('nft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='hello.nft')),
            ],
        ),
    ]
