# Generated by Django 4.2.1 on 2023-07-01 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0024_remove_nft_prices_close_remove_nft_prices_high_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='hello.artwork')),
            ],
        ),
    ]
