# Generated by Django 4.2.1 on 2023-07-01 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0025_artworkpricehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft_bid',
            name='artwork',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bid', to='hello.artwork'),
            preserve_default=False,
        ),
    ]
