# Generated by Django 4.2.1 on 2023-07-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0026_nft_bid_artwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='number_of_sales',
            field=models.IntegerField(default=0),
        ),
    ]
