# Generated by Django 4.2.1 on 2023-07-07 03:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0028_customuser_e_mail_customuser_phone_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='graph_image/')),
                ('NFT', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='hello.nft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
