# Generated by Django 4.2.1 on 2023-07-07 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0029_graph_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graph_Image',
            new_name='GraphImage',
        ),
    ]
