# Generated by Django 4.2.1 on 2023-07-07 23:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0030_rename_graph_image_graphimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkGraphImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artwork_graph_image/')),
                ('Artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graph', to='hello.artwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
