# Generated by Django 4.2.1 on 2023-07-08 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0031_artworkgraphimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art_styles', models.TextField()),
                ('generes', models.TextField()),
                ('mediums', models.TextField()),
                ('historical_periods', models.TextField()),
                ('artists', models.TextField()),
                ('themes', models.TextField()),
                ('colors', models.TextField()),
                ('price_range', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
