# Generated by Django 4.2.1 on 2023-07-08 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0032_interests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interests',
            name='art_styles',
            field=models.CharField(choices=[('realism', 'Realism'), ('abstract', 'Abstract'), ('impressionism', 'Impressionism'), ('cubism', 'Cubism'), ('surrealism', 'Surrealism'), ('pop_art', 'Pop Art'), ('minimalism', 'Minimalism'), ('contemporary', 'Contemporary'), ('street_art', 'Street Art'), ('digital_art', 'Digital Art')], max_length=100),
        ),
        migrations.AlterField(
            model_name='interests',
            name='artists',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='colors',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='generes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='historical_periods',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='mediums',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='price_range',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='interests',
            name='themes',
            field=models.TextField(blank=True),
        ),
    ]
