# Generated by Django 4.2.1 on 2023-07-08 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0033_alter_interests_art_styles_alter_interests_artists_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interests',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='generes',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='historical_periods',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='mediums',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='price_range',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='themes',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='user',
        ),
    ]
