# Generated by Django 4.2.1 on 2023-07-10 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0034_remove_interests_artists_remove_interests_colors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_name', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='project_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='interests',
            name='art_styles',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
