# Generated by Django 4.2.1 on 2023-07-10 01:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0035_projectimages_alter_interests_art_styles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProjectImages',
        ),
        migrations.AddField(
            model_name='interests',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='interests', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
