# Generated by Django 4.2.1 on 2023-07-11 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0036_delete_projectimages_interests_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='generes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='interests',
            name='art_styles',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
