# Generated by Django 4.2.1 on 2023-07-11 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0037_interests_generes_alter_interests_art_styles'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='historical_periods',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='interests',
            name='mediums',
            field=models.TextField(blank=True),
        ),
    ]
