# Generated by Django 4.2.1 on 2023-07-11 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0038_interests_historical_periods_interests_mediums'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000000),
        ),
        migrations.AddField(
            model_name='interests',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10000000),
        ),
    ]
