# Generated by Django 4.2.1 on 2023-07-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0039_interests_max_price_interests_min_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='art_styles',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artwork',
            name='generes',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artwork',
            name='historical_periods',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='artwork',
            name='mediums',
            field=models.TextField(blank=True),
        ),
    ]
