# Generated by Django 4.2.1 on 2023-07-11 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0040_artwork_art_styles_artwork_generes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='art_watchlist',
            field=models.CharField(blank=True, max_length=9000),
        ),
        migrations.AddField(
            model_name='customuser',
            name='nft_watchlist',
            field=models.CharField(blank=True, max_length=9000),
        ),
    ]
