# Generated by Django 4.2.1 on 2023-07-13 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0041_customuser_art_watchlist_customuser_nft_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='interests',
            name='art_styles_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='interests',
            name='generes_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='interests',
            name='historical_periods_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='interests',
            name='mediums_weight',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artwork', models.ManyToManyField(to='hello.artwork')),
                ('nft', models.ManyToManyField(to='hello.nft')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='interests',
            name='watchlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.watchlist'),
        ),
    ]
