# Generated by Django 4.2.1 on 2023-07-13 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0042_interests_art_styles_weight_interests_generes_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='art_watchlist',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='nft_watchlist',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='art_styles_weight',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='generes_weight',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='historical_periods_weight',
        ),
        migrations.RemoveField(
            model_name='interests',
            name='mediums_weight',
        ),
        migrations.AddField(
            model_name='interests',
            name='categories',
            field=models.JSONField(default=dict),
        ),
    ]
