# Generated by Django 4.2.1 on 2023-07-17 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0044_remove_interests_max_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=90000000),
        ),
        migrations.AddField(
            model_name='nft',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=9000000),
        ),
    ]
