# Generated by Django 4.2.1 on 2023-07-26 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0045_artwork_keywords_nft_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='prefs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_growth', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=50)),
                ('time_frame', models.CharField(blank=True, max_length=100)),
                ('min_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('max_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=50)),
                ('sold', models.BooleanField(default=False)),
                ('for_sale', models.BooleanField(default=True)),
                ('want_artwork', models.BooleanField(default=True)),
                ('want_nfts', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prefs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
