# Generated by Django 4.2.1 on 2023-08-04 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0047_alter_prefs_max_price_alter_prefs_min_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='e_mail',
            field=models.EmailField(default='', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_num',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
