# Generated by Django 4.2.1 on 2023-08-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0049_nft_updated_at_alter_artworkpricehistory_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
