# Generated by Django 4.2.1 on 2023-08-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0050_nft_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, default='profile_pictures/profile_placeholder.png', upload_to='profile_pictures/'),
        ),
    ]
