# Generated by Django 4.2.1 on 2023-08-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0051_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='percent_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='pricehistory',
            name='previous_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
