# Generated by Django 4.2.1 on 2023-08-11 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0052_nft_percent_change_pricehistory_previous_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nft',
            name='percent_change',
            field=models.CharField(blank=True, default='', max_length=9000000),
        ),
    ]
