# Generated by Django 4.2.1 on 2023-08-13 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0053_alter_nft_percent_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='percent_change',
            field=models.CharField(blank=True, default='', max_length=9000000),
        ),
        migrations.AddField(
            model_name='artworkpricehistory',
            name='previous_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
